packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  - 'packages-echarts/**'
  - 'packages-shared/**'
  - 'packages-ssg/**'
  - 'packages-trade/**'
  - 'packages-trading-view/**'
  - 'packages-widgets/**'
  - 'deploy'
  - 'scripts'
